routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function(){

    Route::get('/', 'PageController@index')->name('index');
    Route::get('about', 'PageController@about')->name('pages.aboutus');
    Route::get('services', 'PageController@service')->name('pages.service');
    Route::get('structure', 'PageController@structure')->name('pages.structure');
    Route::get('quote', 'PageController@quote')->name('pages.quote');

    Route::get('contact', 'PageController@contact')->name('pages.contactus');
    Route::get('contact/direction', 'PageController@direction');

    Route::get('team', 'PageController@leadership')->name('pages.leadership');
    Route::get('faq', 'PageController@faq')->name('pages.faq');
    Route::get('news-link/{news_slug}', ['as' => 'pages.single', 'uses' => 'PageController@getSingleNewsUrl'])->where('news_slug', '[\w\d\-\_]+');

    Route::resource('categories', 'CategoryController');
    Route::resource('roles', 'RoleController')->except('create');
    Route::resource('news', 'NewsController');
    Route::resource('users', 'UserController')->except('create');


    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');

});

resources/views/partials/footer.blade.php
<div class="container">

	{{-- =================Top Navigation or social media icon=========================== --}}
	<section id="topbar" class="d-none d-lg-block">
	    <div class="container clearfix">
	    {{--  <div class="contact-info float-left">
	        <i class="fa fa-envelope-o"></i> <a href="mailto:info@specifictoolsng.com">info@specifictoolsng.com</a>
	        <i class="fa fa-phone"></i> +23480-000-0000
	      </div>--}}

	      <div class="social-links float-right">
	        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
	        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
	        <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
	        <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
	        <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
	      </div>
	    </div>
	  </section>
	  {{-- =====================End top nav for social media icon============================== --}}

	<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
	<center>
		&copy; 2018 -
	<script type="text/javascript">
		var year = new Date().getFullYear();
		document.write(year);
	</script>
		Specific Tools NG | All Rights Reserved.
	</center>

</div>

resources/views/partials/header.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{-- CSRF TOKEN PROTECTION --}}
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Specific Tools, Power, Mast and Network Installation and Maintenance!')</title>


    {{-- MDB Javascript and JQuery CDN --}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.3/css/mdb.min.css" rel="stylesheet">

    <!-- Fonts -->
   <link rel="dns-prefetch" href="//fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
   <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">

    {{-- Font Awesome --}}
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">



    {{-- cdn and libraries for the NAV Menu --}}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700" rel="stylesheet">
    {{-- Html::style('css/lib/bootstrap/css/bootstrap.min.css') --}}
    {{-- Html::style('css/lib/font-awesome/css/font-awesome.min.css') --}}
    {{-- Html::style('css/lib/animate/animate.min.css') --}}
    {{-- Html::style('css/lib/ionicons/css/ionicons.min.css') --}}
    {{-- Html::style('css/lib/owlcarousel/assets/owl.carousel.min.css') --}}
    {{-- Html::style('css/lib/magnific-popup/magnific-popup.css') --}}
    {{-- Html::style('css/lib/ionicons/css/ionicons.min.css') --}}
    {{ Html::style('css/style.css') }}





    {{ Html::style('css/main.css') }}

    {{-- Load page specific stylesheets --}}
    @yield('stylesheets')

resources/views/partials/messages.blade.php
@if(Session::has('success'))

	<div class="alert alert-success" role="alert">
		<strong>Success: </strong> {{ Session::get('success') }}
	</div>

@endif

@if(count($errors) > 0)

	<div class="alert alert-danger" role="alert">
		<strong>Error(s): </strong>
		<ul>
		@foreach($errors->all() as $error)
		<li>{!! $error !!}</li>
		@endforeach
	</ul>
	</div>

@endif

resources/views/partials/nav.blade.php
<header>
			<div id="navbar" class="container-fluid nav-height">
				<div class="container nav-fill w-100">
					<nav class="navbar navbar-expand-md navbar-light" role="navigation">
						<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarContent">
							<ul class="navbar-nav nav-fill w-100">
                <li class="nav-item">
                  <a href="{{ url('/') }}" role="button" class="btn btn-default"><i class="material-icons md-48">home</i></a>
                </li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('pages.aboutus') }}" role="button" class="btn btn-default">About Us</a>
									  {{-- <button class="btn btn-default dropdown-toggle dropdown-toggle-split d-none d-md-block" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									    <span class="sr-only">Toggle Dropdown</span>
									  </button>
									  <div class="dropdown-menu">
											<a class="dropdown-item" href="#">Item</a>
									  </div> --}}
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="#" role="button" class="btn btn-default">Our Services</a>
									  <button class="btn btn-default dropdown-toggle dropdown-toggle-split d-none d-md-block" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									    <span class="sr-only">Toggle Dropdown</span>
									  </button>
									  <div class="dropdown-menu">
											<a class="dropdown-item" href="#">Service 1</a>
											<a class="dropdown-item" href="#">Service 2</a>
									  </div>
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('pages.structure') }}" role="button" class="btn btn-default">Our Structure</a>
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('pages.contactus') }}" role="button" class="btn btn-default">Contact Us</a>
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('pages.faq') }}" role="button" class="btn btn-default">FAQ</a>
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('news.index') }}" role="button" class="btn btn-default">News</a>
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('login') }}" role="button" class="btn btn-default">Login</a>
									</div>
								</li>
								<li class="nav-item">
									<div class="btn-group">
									  <a href="{{ route('register') }}" role="button" class="btn btn-default">Register</a>
									</div>
								</li>

							</ul>
						</div>
					</nav>
				</div>
			</div>
		</header>

resources/views/partials/navigation.blade.php
{{-- =================Top Navigation or social media icon=========================== --}}
<section id="topbar" class="d-none d-lg-block">
    <div class="container clearfix">
      <div class="contact-info float-left">
        <i class="fa fa-envelope-o"></i> <a href="mailto:info@specifictoolsng.com">info@specifictoolsng.com</a>
        <i class="fa fa-phone"></i> +23480-000-0000
      </div>
      <div class="social-links float-right">
      {{--  <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
        <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
        <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
        <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>--}}
      </div>
    </div>
  </section>
  {{-- =====================End top nav for social media icon============================== --}}

  {{-- ===============================Menu - main navigation=============================== --}}
  <header id="header">
   <div class="container">

     <div id="logo" class="pull-left">
        <!-- Uncomment below if you prefer to use an image logo -->
      <a href="{{ url('/') }}"><img class="logo-pullup" src="{{ asset('logos/FullLogoWhite.png') }}" alt="Specific Tools Logo" /></a>
     </div>

     <nav id="nav-menu-container">
       <ul class="nav-menu">
         <li class="menu-active"><a href="{{ url('/')}}"><img style="max-width:35px;max-height:35px;" src="http://motoraty-media.s3-us-west-2.amazonaws.com/news/wp-content/uploads/2016/10/motoraty-home-page-icon-red.png" alt="Home iCON"> </a></li>
         <li class="menu-has-children"><a href="{{ route('pages.aboutus') }}">About Us</a>
              <ul>
                <li><a href="{{ route('pages.leadership') }}">Leadership Team</a></li>
              </ul>
            </li>
         <li><a href="{{ route('pages.structure') }}">Our Structure</a></li>
         <li><a href="{{ route('pages.service') }}">Services</a></li>

      <!--   <li class="menu-has-children"><a href="{{ route('pages.service') }}">Leadership Team</a>
           <ul>
             <li><a href="#">Service 1</a></li>
             <li><a href="#">Service 2</a></li>
             <li><a href="#">Service 3</a></li>
           </ul>
         </li>-->

         {{-- <li><a href="{{ url('/') }}#our-contact">Contact</a></li> --}} <!-- ==================How to link route to ID tag on a div -->
         <li><a href="{{ route('pages.contactus') }}">Contact</a></li>
         <li><a href="{{ route('news.index') }}">News</a></li>
         <li><a href="{{ route('pages.faq')}}">FAQ</a></li>

      {{--   <li class="menu-has-children"><a href="#">Staff Portal</a>
            <ul>
              @guest
                  <li class="nav-item">
                      <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                  </li>
                  @if (Route::has('register'))
                      <li class="nav-item">
                          <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                      </li>
                  @endif
            </ul>
          </li>--}}
        @guest
        <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>

         @else
         <li><a href="{{ route('news.index') }}">{{ __('All News') }}</a></li>

         @if(Auth::user()->roles("Administrator"))
         <li><a href="{{ route('news.create') }}">{{ __('Add News') }}</a></li>
         <li><a href="{{ route('roles.index') }}">{{ __('Roles | Access') }}</a></li>
         <li><a href="{{ route('users.index') }}">{{ __('Users | Access Control') }}</a></li>
         @endif
         <li class="menu-has-children"><a href="#">{{ Auth::user()->othernames }} {{ Auth::user()->surname }} <span class="caret"></span></a>
           <ul>
             <li>
               <a class="dropdown-item" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>

            </li>
           </ul>
         </li>
         @endguest


       </ul>
     </nav>
   </div>
 </header>
 {{-- ======================end main navigation================================= --}}

resources/views/partials/scripts.blade.php
{{-- MDB Javascript and JQuery CDN --}}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{{-- Bootstrap tooltips --}}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
{{-- Bootstrap core JavaScript --}}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
{{-- MDB core JavaScript --}}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.3/js/mdb.min.js"></script>


<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>



{{-- JavaScript Libraries --}}
{{ Html::script('js/lib/jquery/jquery.min.js') }}
{{ Html::script('js/lib/jquery/jquery-migrate.min.js') }}
{{ Html::script('js/lib/bootstrap/js/bootstrap.bundle.min.js') }}
{{ Html::script('js/lib/easing/easing.min.js') }}
{{ Html::script('js/lib/superfish/hoverIntent.js') }}
{{ Html::script('js/lib/superfish/superfish.min.js') }}
{{ Html::script('js/lib/wow/wow.min.js') }}
{{ Html::script('js/lib/owlcarousel/owl.carousel.min.js') }}
{{ Html::script('js/lib/magnific-popup/magnific-popup.min.js') }}
{{ Html::script('js/lib/sticky/sticky.js') }}
{{ Html::script('js/main.js') }}

resources/views/partials/uimain.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>

   {{-- including partial --}}
  @include('partials.header')

  <!--Add page specific stylesheets here-->

</head>

<body>

    @include('partials.navigation')

    <div class="well">

        @include('partials.messages') <!--error messages -->

          @yield('content')


    </div>

      <hr/>
      @include('partials.footer')
</div>


    @include('partials.scripts')

    {{--Load specific javascript for pages --}}
    @yield('javascripts')
</body>
</html>