routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function(){

    Route::get('/', 'PageController@index')->name('index');
    Route::get('about', 'PageController@about')->name('pages.aboutus');
    Route::get('services', 'PageController@service')->name('pages.service');
    Route::get('structure', 'PageController@structure')->name('pages.structure');
    Route::get('quote', 'PageController@quote')->name('pages.quote');

    Route::get('contact', 'PageController@contact')->name('pages.contactus');
    Route::get('contact/direction', 'PageController@direction');

    Route::get('team', 'PageController@leadership')->name('pages.leadership');
    Route::get('faq', 'PageController@faq')->name('pages.faq');
    Route::get('news-link/{news_slug}', ['as' => 'pages.single', 'uses' => 'PageController@getSingleNewsUrl'])->where('news_slug', '[\w\d\-\_]+');

    Route::resource('categories', 'CategoryController');
    Route::resource('roles', 'RoleController')->except('create');
    Route::resource('news', 'NewsController');
    Route::resource('users', 'UserController')->except('create');


    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'surname', 'othernames', 'mobile', 'email', 'password','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

//=========================Many to many rela
    public function roles()
    {
      return $this->belongsToMany('App\Role'); //User has many Roles
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use Illuminate\Http\Request;
use Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //show all users
        $users = User::orderBy('created_at', 'desc')->paginate(10);

        return view('users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate and create user
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {

        return view('users.profile', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //show editable form for user
        $roles = Role::all();
        $roleList = array();
        foreach ($roles as $role)
        {
          $roleList[$role->id] = $role->name;
        }

        return view('users.edit', ['user' => $user], ['roles' => $roleList]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //validate and update user password
        $this->validate($request, array(
          'roles' => 'required'
        ));

        //sync tag associations
       if(isset($request->roles))
       {
         $user->roles()->sync($request->roles);
       }else{
         $user->roles()->sync(array()); //if not tag select, show empty array
       }

        Session::flash('success', 'Permission was successfuly Updated!');
        //Redirect user to the Post homepage
        return redirect()->route('users.show', $user->id);

    }

    public function delete()
    {
      return view('users.delete');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //delete user
        $user = User::FindOrFail($user->id);
        $user->roles()->detach(); //deassociate permissions

        $user->delete();
        return redirect()->route('users.index')->with('success', 'User Successfuly Deleted');
    }
}

resources/views/users/delete.blade.php
@extends('partials.uimain')

@section('title', '| Users')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}


@endsection

@section('content')

  <div class="row space-top">
    <div class="col-4 offset-2">
      <h2>Delete User ?</h2>

      {!! Form::open(['route' => ['users.destory', $user->d], 'method' => 'DELETE']) !!}
        {{Form::submit('Delete', array('class' => 'btn btn-danger btn block'))}}
      {!! Form::close() !!}

    </div>
  </div>

@endsection

resources/views/users/edit.blade.php
@extends('partials.uimain')

@section('title', '| Edit Role')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}
    {!! Html::style('css/select2.min.css') !!}

@endsection

@section('content')

    <div class="row space-top">

      <div class="col-6 offset-3">
        {{ Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'PUT']) }}
          <br/>          <br/>          <br/>
          <h3 class="text-center text-primary">Edit Permission</h3>
          <h3 class="text-capitalize text-danger">{{ $user->othernames }} {{ $user->surname }}</h3>
          {{ Form::label('roles', 'Select Permission(s)', ['class' => 'form-spacing']) }}
    			{{ Form::select('roles[]', $roles, null, ['class' => 'form-control select2-multi-tags', 'multiple' => 'multiple']) }}
          {{ Form::submit('Save Changes', ['class' => 'btn btn-primary btn-block form-spacing'])}}

        {!! Form::close() !!}
      </div>
      <div class="col-sm-4 offset-4">
						{!! Html::linkRoute('users.index', 'Cancel', array('class' => 'btn btn-danger btn-block')) !!}
			</div>

    </div>

@endsection

@section('javascripts')

	{!! Html::script('js/select2.min.js') !!}

	<script type="text/javascript">
			$('.select2-multi-tags').select2();
	</script>

@endsection

resources/views/users/index.blade.php
@extends('partials.uimain')

@section('title', '| Users')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}


@endsection

@section('content')

  <div class="row space-top">
    <div class="col-6 offset-2">
      <h2 class="text-center">Users | Permissions</h2>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Permission(s)</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
              <td><a href="{{ route('users.show', $user->id)}}"> {{ $user->othernames }} {{ $user->surname}}</a></td>
              <td><a href="{{ route('users.show', $user->id)}}"> {{ $user->email }} </a></td>
              <td><a href="{{ route('users.show', $user->id)}}"> {{ $user->mobile }} </a></td>
              <td><a href="#">
                @foreach($user->roles as $role)
                  <li class="label label-default">{{ $role->name }}</li>
                @endforeach
              </a></td>
              <td>
                <a class="btn btn-primary btn-sm" href="{{route('users.edit', $user->id)}}"><i class="fa fa-pencil"></i> Edit</a>
                <a class="btn btn-primary btn-sm" href="{{route('users.show', $user->id)}}"><i class="fa fa-pencil"></i> View</a>
              {{--  <a class="btn btn-primary btn-sm" href="{{route('users.destroy', $user->id)}}"><i class="fa fa-pencil"></i> Delete</a>--}}
              </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>

{{--    <div class="col-md-2"> <!--Form for creating category -->
      <div class="well">
        {!! Form::open(['route' => 'user.store', 'method' => 'POST']) !!}
                  <br/>          <br/>          <br/>
          <h4 class="text-center text-primary">Create User</h3>

          {{ Form::text('surname', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Surnname'])}}
          {{ Form::textarea('othernames', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Other Names'])}}
          {{ Form::email('email', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Email Address'])}}
          {{ Form::password('password', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Password'])}}
          {{ Form::submit('Add User', ['class' => 'btn btn-primary btn-block form-spacing'])}}

        {!! Form::close() !!}
      </div>
    </div>--}}
  </div>

@endsection

resources/views/users/profile.blade.php
@extends('partials.uimain')

@section('title', '| User Profile, Permissions')

@section('content')

  <div class="row space-top">
    <div class="col-6 offset-2">
      <h2 class="text-center">User's Permission(s)</h2>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Email Address</th>
            <th>Full Name</th>
            <th>Permission(s)</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td> {{ $user->email }}</td>
              <td> {{ $user->surname }} {{ $user->othernames }}</td>
              <td>
                @foreach($user->roles as $role)
                  <li class="label label-default">{{ $role->name }}</li>
                @endforeach
              </td>
              <td>
                <a class="btn btn-primary btn-sm" href="{{route('users.edit', $user->id)}}"><i class="fa fa-pencil"></i> Edit</a>
              </td>
            </tr>
        </tbody>
      </table>
    </div>


  </div>

@endsection