routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function(){

    Route::get('/', 'PageController@index')->name('index');
    Route::get('about', 'PageController@about')->name('pages.aboutus');
    Route::get('services', 'PageController@service')->name('pages.service');
    Route::get('structure', 'PageController@structure')->name('pages.structure');
    Route::get('quote', 'PageController@quote')->name('pages.quote');

    Route::get('contact', 'PageController@contact')->name('pages.contactus');
    Route::get('contact/direction', 'PageController@direction');

    Route::get('team', 'PageController@leadership')->name('pages.leadership');
    Route::get('faq', 'PageController@faq')->name('pages.faq');
    Route::get('news-link/{news_slug}', ['as' => 'pages.single', 'uses' => 'PageController@getSingleNewsUrl'])->where('news_slug', '[\w\d\-\_]+');

    Route::resource('categories', 'CategoryController');
    Route::resource('roles', 'RoleController')->except('create');
    Route::resource('news', 'NewsController');
    Route::resource('users', 'UserController')->except('create');


    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //fillable fields
    protected $fillable = [
      'categoryName',
      'description'
    ];


    //one to many relationship, A Category has Many news assigned to it
    public function news()
    {
      return $this->hasMany('App\News');
    }


}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/categories/index.blade.php
@extends('partials.uimain')

@section('title', '| Available News Categories')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}

    {!! Html::style('css/parsley.css') !!}
	  {!! Html::style('css/select2.min.css') !!}



@endsection



@section('content')

  <div class="card">
    <div class="card-title">
      <h4 class="text-center">Available Movie Categories</h4>
    </div>
    <div class="card-body">
      <div class="table-responsive">
      <div class="col-md-5 col-md-offset-3">
          <table class="table mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shaddow--2dp customTable">
            <thead>
            <th>Category</th>
            <th>Description</th>
            <th>
              Actions
            </th>
        </thead>

        <tbody>
          @foreach($categories as $category)
          <tr>
            <td>{{ $category->categoryName }}</td>
            <td>{{ $category->description }}</td>
            <td>
              <a href="{{ route('categories.show', $category->id)}}" class="btn btn-primary btn-sm">View</a>
              <a href="{{ route('categories.show', $category->id)}}" class="btn btn-sm btn-warning">Suspend</a>
              <a href="{{ route('categories.destroy', $category->id)}}" class="btn btn-sm btn-danger">Delete</a>

            </td>
          </tr>
          @endforeach
        </tbody>
        </table>
      </div>

      <div class="col-md-3 pull-right">
          <div class="well">

            <h4 class="text-center">Add New Category</h4>

        {!! Form::open(array('route' => 'categories.store', 'data-parsley-validate' => '', 'method' => 'post')) !!}

          {{ Form::text('categoryName', null, array('class' => 'form-control', 'placeholder' => 'Category Name', 'required' => '', 'maxlength' => '120')) }}
          {{ Form::textarea('description', null, array('class' => 'form-control form-spacing', 'placeholder' => 'Enter Descrption for this Category', 'data-parsley-trigger' => 'change', 'maxlength' => '1000')) }}

          {{ Form::submit('Create Category', array('class' => 'btn btn-success btn-sm btn-block btn-top-spacing')) }}


      {!! Form::close() !!}
    </div>
  </div>
</div>
</div>
</div>



@endsection


@section('scripts')

    {{--Load Page specific script that will only affect this page --}}

    {!! Html::script('js/parsley.min.js') !!}
	  {!! Html::script('js/select2.min.js') !!}

	<script type="text/javascript">
			$('.select2-multi-tags').select2();
	</script>

@endsection