routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function(){

    Route::get('/', 'PageController@index')->name('index');
    Route::get('about', 'PageController@about')->name('pages.aboutus');
    Route::get('services', 'PageController@service')->name('pages.service');
    Route::get('structure', 'PageController@structure')->name('pages.structure');
    Route::get('quote', 'PageController@quote')->name('pages.quote');

    Route::get('contact', 'PageController@contact')->name('pages.contactus');
    Route::get('contact/direction', 'PageController@direction');

    Route::get('team', 'PageController@leadership')->name('pages.leadership');
    Route::get('faq', 'PageController@faq')->name('pages.faq');
    Route::get('news-link/{news_slug}', ['as' => 'pages.single', 'uses' => 'PageController@getSingleNewsUrl'])->where('news_slug', '[\w\d\-\_]+');

    Route::resource('categories', 'CategoryController');
    Route::resource('roles', 'RoleController')->except('create');
    Route::resource('news', 'NewsController');
    Route::resource('users', 'UserController')->except('create');


    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');

});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //protected fillabes
    protected $fillable = ['name', 'role_description'];







    //===================Many to Many Relationship===========
    public function users()
    {
      return $this->belongsToMany('App\User'); // A user has many roles or belongs to Many roles
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;
use Session;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //sho all roles
        $roles = Role::paginate(10);
        return view('roles.index', compact('roles', $roles));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate role
        $this->validate($request, array(
          'name' => ['required', 'min:3', 'max:64', 'string'],
          'role_description' => ['string', 'max:1000']
        ));

        //create role
        Role::create($request->all());

        Session::flash('success', 'New Role Successfully Added');
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //show a single role
        return view('roles.show', compact('role', $role));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        //show edit form
        return view('roles.modify', compact('role', $role));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        //update role , validate first
        $this->validate($request, array(
          'name' => ['required', 'min:3', 'max:64', 'string'],
          'role_description' => ['string', 'max:1000']
        ));

        //create role

        $role->update($request->all());

        Session::flash('success', 'Role Update Success!');
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //delete role
        //deleting tags and it associate and all Posts linked to it
        try {
          $role = Role::findOrFail($role->id);
          $role->users()->detach(); //remove the role from the users assigned to
        } catch (ModelNotFoundException $e) {
          dd(get_class_methods($e)); // lists all available methods for exception object
          dd($e);
        }
        //delete the actual Tag now
        $role->delete();
        //flash message
        Session::flash('success', 'Role Successfully Deleted');
        return redirect()->route('roles.index');
    }
}

resources/views/roles/index.blade.php
@extends('partials.uimain')

@section('title', '| Available Roles')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}


@endsection

@section('content')

  <div class="row space-top">
    <div class="col-6 offset-2">
      <h2 class="text-center">Roles | Permissions</h2>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @foreach($roles as $role)
            <tr>
              <td><a href="{{ route('roles.show', $role->id)}}"> {{ $role->name }} </a></td>
              <td><a href="{{ route('roles.show', $role->id)}}"> {{ $role->role_description }} </a></td>
              <td>
                <a class="btn btn-primary btn-sm" href="{{route('roles.edit', $role->id)}}"><i class="fa fa-pencil"></i> Edit</a>
        {{--        {!! Form::open(['route' => ['roles.destroy', $role->id], 'method' => 'DELETE']) !!}
                  {!! Form::submit('Delete', array('class' => 'btn btn-danger btn-sm')) !!}
                {!! Form::close() !!}     --}}
              </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>

{{--    <div class="col-md-2"> <!--Form for creating category -->
      <div class="well">
        {!! Form::open(['route' => 'roles.store', 'method' => 'POST']) !!}
                  <br/>          <br/>          <br/>
          <h4 class="text-center text-primary">Create New Role</h3>

          {{ Form::text('name', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Role Name'])}}
          {{ Form::textarea('role_description', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Role Description'])}}
          {{ Form::submit('Add Role', ['class' => 'btn btn-primary btn-block form-spacing'])}}

        {!! Form::close() !!}
      </div>
    </div>--}}
  </div>

@endsection

resources/views/roles/modify.blade.php
@extends('partials.uimain')

@section('title', '| Edit Role')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}


@endsection

@section('content')

    <div class="row space-top">

      <div class="col-6 offset-3">
        {{ Form::model($role, ['route' => ['roles.update', $role->id], 'method' => 'PUT']) }}
          <br/>          <br/>          <br/>
          <h4 class="text-center text-primary">Edit Role</h3>
          {{ Form::text('name', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Role Name'])}}
          {{ Form::textarea('role_description', null, ['class' => 'form-control form-spacing', 'placeholder' => 'Role Description'])}}
          {{ Form::submit('Save Changes', ['class' => 'btn btn-primary btn-block form-spacing'])}}

        {!! Form::close() !!}
      </div>
      <div class="col-4 offset-4">
          {!! Html::linkRoute('roles.index', 'Cancel', array('class' => 'btn btn-danger btn-block')) !!}
      </div>

    </div>


@endsection

resources/views/roles/show.blade.php
@extends('partials.uimain')

@section('title', '| Role and Users')


@section('stylesheets')

    {{--Load page specific stylesheets that will only affect this page --}}

@endsection

@section('content')

  <div class="row space-top">
    <div class="col-8 offset-2">
      <h2>{{ $role->name }} Role <small>{{$role->users()->count() }} Users</small></h2>
    </div>
    <div class="col-md-2">
      <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-sm btn-primary pull-right btn-block" style="margin-top:20px;">Edit</a>
    </div>
    <div class="col-md-2">
      {{ Form::open(['route' => ['roles.destroy', $role->id], 'method' => 'DELETE']) }}
        {{ Form::submit('Delete Role', ['class' => 'btn btn-danger btn-block', 'style' => 'margin-top:20px;']) }}
      {{ Form::close() }}
    </div>
  </div>

    <div class="row">
      <div class="col-md-12">
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>User</th>
              <th>Role(s) | Permission(s)</th>
              <th></th>
            </tr>
          </thead>
            <tbody>
              @foreach($role->users as $user)
                <tr>
                  <th>{{ $user->id }}</th>
                  <td>{{ $user->othernames }}</td>
                  <td>
                    @foreach($user->roles as $role)
                      <span class="label label-default">{{ $role->name }}</span>
                    @endforeach
                  </td>
                  <td><a href="{{ route('users.show', $user->id) }}" class="btn btn-xs btn-default">View</a></td>
                </tr>
              @endforeach
            </tbody>
        </div>
      </div>
    </div>




@endsection